### ISSUE TITLE
Duplicate emails should not be allowed for separate users

### ISSUE THREAD

**Issue by dmitrizzle** [roast-cms/analog-cafe-server#245]
A user should not be able to create another account with the email already in use by another user. 
<img width="852" alt="screen shot 2018-04-04 at 12 03 05 pm" src="https://user-images.githubusercontent.com/8587882/38289484-a59c0de8-3800-11e8-8a99-102a21a0cfce.png">

**Comment by ice5050** [comment]
What should we do with the users without email? (They are from twitter).

**Comment by ice5050** [comment]
And for the migration what should we do if it has been already duplicated? (As in the screenshot)

**Comment by dmitrizzle** [comment]
No need to worry about the existing duplicates, there aren't that many users so I can go through the DB and clean by hand.

Are we able to get email address from Twitter/Facebook for the user?

**Comment by dmitrizzle** [comment]
Closing. I will create a front-end app to request Twitter users to add their emails: https://github.com/roast-cms/analog-cafe-server/issues/284
